* tmux
** Basic Usage

   | prefix ?                  | help                    |
   |---------------------------+-------------------------|
   |                           |                         |
   | prefix prefix             | jump to last window     |
   | prefix <0..9>             | select window           |
   | prefix _                  | split window vertical   |
   | prefix \vert              | split window horizontal |
   | prefix ,                  | rename window           |
   |                           |                         |
   |---------------------------+-------------------------|
   |                           |                         |
   | prefix Up/Down/Left/Right | select pane             |
   | prefix x                  | delete pane             |
   |                           |                         |
   |---------------------------+-------------------------|
   | prefix [                  | Enter copy mode         |
   | prefix ]                  | Past copied items       |
   |                           |                         |

** Installation and Upgrade
   - http://stackoverflow.com/questions/25940944/ugrade-tmux-from-1-8-to-1-9-on-ubuntu-14-04
   - https://bogdanvlviv.com/posts/tmux/how-to-install-the-latest-tmux-on-ubuntu-16_04.html

     #+BEGIN_SRC shell
       sudo apt install pkg-config libevent-dev libncurses5-dev
       git clone https://github.com/tmux/tmux.git /tmp/tmux
       cd /tmp/tmux
       git checkout 2.7
       ./autogen.sh
       ./configure --prefix='/usr/local/stow/tmux-2.7'
       make
       sudo make install
     #+END_SRC


** Attach/resume
   | tmux attach                               | as screen -r            |
   | tmux attach -t session-id                 | as screen -r session-id |
   | ssh sherman_hsu@10.20.0.12 -t tmux attach | Connect remote tmux     |
** Custom session name
   | tmux new -s session-name |
** List all sessions
   | tmux ls  | as screen ls |
   | prefix s | choose-tree (list sessions) |
** Switch to specific window
   | prefix w | Interactive index to choose from 0-9a-z |
   | prefix ' | Input window index                      |
** Swap or reorder windows
   | swap-windows -s WINDOW_INDEX1 -t WINDOW_INDEX2 | Swap WINDOW_INDEX1 with WINDOW_INDEX2 |
   | swap-windows -t DIST_WINDOW_INDEX              | Swap to window index                  |
** Move window between tmux clients
   | swap-windows -s SRC_CLIENT:WINDOW -t DEST_CLIENT | Move WINDOW from SRC_CLIENT to DEST_CLIENT |
** How to quickly switch to 10+ windows in tmux
   | C-] ' | Select the window index |
   | C-] w | Get an ineractive index to choose from (0-9a-z) |
** Enlarge window for full size
   | C-] D | choose to detach other client that using small size window |
** Send key to target session, window, pane
   - Send "ls"
   #+BEGIN_SRC sh
   tmux attach \; send -t <session>:<window>.<pane [optional]> ls ENTER
   # or
   tmux send -t <session>:<window>.<pane [optional]> ls ENTER
   #+END_SRC
* tmux.conf
** Sample

   #+BEGIN_SRC sh
   /usr/share/doc/tmux/examples/vim-keys.conf
   /usr/share/doc/tmux/examples/screen-keys.conf
   #+END_SRC

* tmuxinator
  - Create and manage tmux sessions easily.
  - https://github.com/tmuxinator/tmuxinator
* Tmux Plugin Manager (tpm)
  - https://github.com/tmux-plugins/tpm
** Installation

   #+BEGIN_SRC sh
   # Clone TPM
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

   # Put this at the bottom of .tmux.conf:
   # List of plugins
   set -g @plugin 'tmux-plugins/tpm'
   set -g @plugin 'tmux-plugins/tmux-sensible'

   # Other examples:
   # set -g @plugin 'github_username/plugin_name'
   # set -g @plugin 'git@github.com/user/plugin'
   # set -g @plugin 'git@bitbucket.com/user/plugin'

   # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
   run '~/.tmux/plugins/tpm/tpm'

   # type this in terminal
   tmux source ~/.tmux.conf
   #+END_SRC

* Tmux useful plugins
**  https://github.com/tmux-plugins/tmux-yank

    Normal Mode

        ~prefix-y~ — copies text from the command line to the clipboard.

        Works with all popular shells/repls. Tested with:
            shells: bash, zsh (with bindkey -e), tcsh
            repls: irb, pry, node, psql, python, php -a, coffee
            remote shells: ssh, mosh
            vim/neovim command line (requires vim-husk or vim-rsi plugin)

        ~prefix-Y~ — copy the current pane's current working directory to the clipboard.

    Copy Mode
        y - copy selection to system clipboard.
        Y (shift-y) - "put" selection. Equivalent to copying a selection, and pasting it to the command line.

** To Be Tried

  https://github.com/tmux-plugins/tmux-resurrect
  https://github.com/tmux-plugins/tmux-fpp
  https://github.com/tmux-plugins/tmux-logging
  https://github.com/tmux-plugins/tmux-prefix-highlight
  https://github.com/tmux-plugins/tmux-sensible
  https://github.com/tmux-plugins/tmux-pain-control
  https://github.com/tmux-plugins/tmux-sidebar
  https://github.com/tmux-plugins/tmux-sessionist
  https://github.com/tmux-plugins/tmux-copycat
  https://github.com/tmux-plugins/tmux-continuum
